name: receipt_calculator
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  mockito: ^5.4.2
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true
