# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: FlutterCodeQuality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with: 
          flutter-version: '3.10.6'
          
      - name: Install package
        run: flutter pub get
        
      - name: Analyze
        run: flutter analyze
        
      - name: Format
        run: dart format -o none --set-exit-if-changed ./lib
        
      - name: Test
        run: flutter test
